const divisions = [
  {
    id: 1,
    name: "Barisal",
    bengaliName: "বরিশাল",
    districts: [
      {
        id: 1,
        name: "Barguna",
        bengaliName: "বরগুনা",
        upazilas: [
          { id: 1, name: "Amtali", bengaliName: "আমতলী" },
          { id: 2, name: "Bamna", bengaliName: "বামনা" },
          { id: 3, name: "Barguna Sadar", bengaliName: "বরগুনা সদর" },
          { id: 4, name: "Betagi", bengaliName: "বেতাগী" },
          { id: 5, name: "Patharghata", bengaliName: "পাথরঘাটা" },
          { id: 6, name: "Taltali", bengaliName: "তালতলী" },
        ],
      },
      {
        id: 2,
        name: "Barishal",
        bengaliName: "বরিশাল",
        upazilas: [
          { id: 7, name: "Agailjhara", bengaliName: "আগৈলঝাড়া" },
          { id: 8, name: "Babuganj", bengaliName: "বাবুগঞ্জ" },
          { id: 9, name: "Bakerganj", bengaliName: "বাকেরগঞ্জ" },
          { id: 10, name: "Banaripara", bengaliName: "বানারীপাড়া" },
          { id: 11, name: "Gaurnadi", bengaliName: "গৌরনদী" },
          { id: 12, name: "Hizla", bengaliName: "হিজলা" },
          { id: 13, name: "Barishal Sadar", bengaliName: "বরিশাল সদর" },
          { id: 14, name: "Mehendiganj", bengaliName: "মেহেন্দিগঞ্জ" },
          { id: 15, name: "Muladi", bengaliName: "মুলাদী" },
          { id: 16, name: "Wazirpur", bengaliName: "ওয়াজিরপুর" },
        ],
      },
      {
        id: 3,
        name: "Bhola",
        bengaliName: "ভোলা",
        upazilas: [
          { id: 17, name: "Bhola Sadar", bengaliName: "ভোলা সদর" },
          { id: 18, name: "Burhanuddin", bengaliName: "বুরহানউদ্দিন" },
          { id: 19, name: "Char Fasson", bengaliName: "চর ফ্যাশন" },
          { id: 20, name: "Daulatkhan", bengaliName: "দৌলতখান" },
          { id: 21, name: "Lalmohan", bengaliName: "লালমোহন" },
          { id: 22, name: "Manpura", bengaliName: "মনপুরা" },
          { id: 23, name: "Tazumuddin", bengaliName: "তজুমদ্দিন" },
        ],
      },
      {
        id: 4,
        name: "Jhalokati",
        bengaliName: "ঝালকাঠি",
        upazilas: [
          { id: 24, name: "Jhalokati Sadar", bengaliName: "ঝালকাঠি সদর" },
          { id: 25, name: "Kathalia", bengaliName: "কাঠালিয়া" },
          { id: 26, name: "Nalchity", bengaliName: "নলছিটি" },
          { id: 27, name: "Rajapur", bengaliName: "রাজাপুর" },
        ],
      },
      {
        id: 5,
        name: "Patuakhali",
        bengaliName: "পটুয়াখালী",
        upazilas: [
          { id: 28, name: "Bauphal", bengaliName: "বাউফল" },
          { id: 29, name: "Dashmina", bengaliName: "দশমিনা" },
          { id: 30, name: "Galachipa", bengaliName: "গলাচিপা" },
          { id: 31, name: "Kalapara", bengaliName: "কলাপাড়া" },
          { id: 32, name: "Mirzaganj", bengaliName: "মির্জাগঞ্জ" },
          { id: 33, name: "Patuakhali Sadar", bengaliName: "পটুয়াখালী সদর" },
          { id: 34, name: "Rangabali", bengaliName: "রাঙ্গাবালী" },
          { id: 35, name: "Dumki", bengaliName: "ডুমকী" },
        ],
      },
      {
        id: 6,
        name: "Pirojpur",
        bengaliName: "পিরোজপুর",
        upazilas: [
          { id: 36, name: "Bhandaria", bengaliName: "ভান্ডারিয়া" },
          { id: 37, name: "Kawkhali", bengaliName: "কাউখালী" },
          { id: 38, name: "Mathbaria", bengaliName: "মঠবাড়িয়া" },
          { id: 39, name: "Nazirpur", bengaliName: "নাজিরপুর" },
          { id: 40, name: "Pirojpur Sadar", bengaliName: "পিরোজপুর সদর" },
          {
            id: 41,
            name: "Nesarabad (Swarupkati)",
            bengaliName: "নেছারাবাদ (স্বরূপকাঠি)",
          },
          { id: 42, name: "Indurkani", bengaliName: "ইন্দুরকানী" },
        ],
      },
    ],
  },
  {
    id: 2,
    name: "Chittagong",
    bengaliName: "চট্টগ্রাম",
    districts: [
      {
        id: 7,
        name: "Bandarban",
        bengaliName: "বান্দরবান",
        upazilas: [
          { id: 43, name: "Ali Kadam", bengaliName: "আলী কদম" }, // Start upazila ID from 43
          { id: 44, name: "Bandarban Sadar", bengaliName: "বান্দরবান সদর" },
          { id: 45, name: "Lama", bengaliName: "লামা" },
          { id: 46, name: "Naikhongchhari", bengaliName: "নাইক্ষ্যংছড়ি" },
          { id: 47, name: "Rowangchhari", bengaliName: "রোয়াংছড়ি" },
          { id: 48, name: "Ruma", bengaliName: "রুমা" },
          { id: 49, name: "Thanchi", bengaliName: "থানচি" },
        ],
      },
      {
        id: 8,
        name: "Brahmanbaria",
        bengaliName: "ব্রাহ্মণবাড়িয়া",
        upazilas: [
          { id: 50, name: "Akhaura", bengaliName: "আখাউড়া" }, // Continue incrementing upazila ID
          { id: 51, name: "Bancharampur", bengaliName: "বাঞ্ছারামপুর" },
          {
            id: 52,
            name: "Brahmanbaria Sadar",
            bengaliName: "ব্রাহ্মণবাড়িয়া সদর",
          },
          { id: 53, name: "Kasba", bengaliName: "কসবা" },
          { id: 54, name: "Nabinagar", bengaliName: "নবীনগর" },
          { id: 55, name: "Nasirnagar", bengaliName: "নাসিরনগর" },
          { id: 56, name: "Sarail", bengaliName: "সরাইল" },
          { id: 57, name: "Ashuganj", bengaliName: "আশুগঞ্জ" },
          { id: 58, name: "Bijoynagar", bengaliName: "বিজয় নগর" },
        ],
      },
      {
        id: 9,
        name: "Chandpur",
        bengaliName: "চাঁদপুর",
        upazilas: [
          { id: 59, name: "Chandpur Sadar", bengaliName: "চাঁদপুর সদর" },
          { id: 60, name: "Faridganj", bengaliName: "ফরিদগঞ্জ" },
          { id: 61, name: "Haimchar", bengaliName: "হাইমচর" },
          { id: 62, name: "Haziganj", bengaliName: "হাজীগঞ্জ" },
          { id: 63, name: "Kachua", bengaliName: "কচুয়া" },
          { id: 64, name: "Matlab Dakshin", bengaliName: "মতলব দক্ষিণ" },
          { id: 65, name: "Matlab Uttar", bengaliName: "মতলব উত্তর" },
          { id: 66, name: "Shahrasti", bengaliName: "শাহরাস্তি" },
        ],
      },
      {
        id: 10,
        name: "Chittagong",
        bengaliName: "চট্টগ্রাম",
        upazilas: [
          { id: 67, name: "Anwara", bengaliName: "আনোয়ারা" },
          { id: 68, name: "Banshkhali", bengaliName: "বাঁশখালী" },
          { id: 69, name: "Boalkhali", bengaliName: "বোয়ালখালী" },
          { id: 70, name: "Chandanaish", bengaliName: "চন্দনাইশ" },
          { id: 71, name: "Fatikchhari", bengaliName: "ফটিকছড়ি" },
          { id: 72, name: "Hathazari", bengaliName: "হাটহাজারী" },
          { id: 73, name: "Karnaphuli", bengaliName: "কর্ণফুলী" },
          { id: 74, name: "Lohagara", bengaliName: "লোহাগাড়া" },
          { id: 75, name: "Mirsharai", bengaliName: "মিরসরাই" },
          { id: 76, name: "Patiya", bengaliName: "পটিয়া" },
          { id: 77, name: "Rangunia", bengaliName: "রাঙ্গুনিয়া" },
          { id: 78, name: "Raozan", bengaliName: "রাউজান" },
          { id: 79, name: "Sandwip", bengaliName: "সন্দ্বীপ" },
          { id: 80, name: "Satkania", bengaliName: "সাতকানিয়া" },
          { id: 81, name: "Sitakunda", bengaliName: "সীতাকুণ্ড" },
        ],
      },
      {
        id: 11,
        name: "Comilla",
        bengaliName: "কুমিল্লা",
        upazilas: [
          { id: 82, name: "Barura", bengaliName: "বরুড়া" },
          { id: 83, name: "Brahmanpara", bengaliName: "ব্রাহ্মণপাড়া" },
          { id: 84, name: "Burichang", bengaliName: "বুড়িচং" },
          { id: 85, name: "Chandina", bengaliName: "চান্দিনা" },
          { id: 86, name: "Chauddagram", bengaliName: "চৌদ্দগ্রাম" },
          { id: 87, name: "Daudkandi", bengaliName: "দাউদকান্দি" },
          { id: 88, name: "Debidwar", bengaliName: "দেবিদ্বার" },
          { id: 89, name: "Homna", bengaliName: "হোমনা" },
          { id: 90, name: "Laksam", bengaliName: "লাকসাম" },
          { id: 91, name: "Lalmai", bengaliName: "লালমাই" },
          { id: 92, name: "Muradnagar", bengaliName: "মুরাদনগর" },
          { id: 93, name: "Nangalkot", bengaliName: "নাঙ্গলকোট" },
          {
            id: 94,
            name: "Cumilla Adarsha Sadar",
            bengaliName: "কুমিল্লা আদর্শ সদর",
          },
          { id: 95, name: "Meghna", bengaliName: "মেঘনা" },
          { id: 96, name: "Titas", bengaliName: "তিতাস" },
          { id: 97, name: "Monohargonj", bengaliName: "মনোহরগঞ্জ" },
          {
            id: 98,
            name: "Cumilla Sadar Dakshin",
            bengaliName: "কুমিল্লা সদর দক্ষিণ",
          },
        ],
      },
      {
        id: 12,
        name: "Cox's Bazar",
        bengaliName: "কক্সবাজার",
        upazilas: [
          { id: 99, name: "Chakaria", bengaliName: "চকরিয়া" },
          { id: 100, name: "Cox's Bazar Sadar", bengaliName: "কক্সবাজার সদর" },
          { id: 101, name: "Kutubdia", bengaliName: "কুতুবদিয়া" },
          { id: 102, name: "Maheshkhali", bengaliName: "মহেশখালী" },
          { id: 103, name: "Ramu", bengaliName: "রামু" },
          { id: 104, name: "Teknaf", bengaliName: "টেকনাফ" },
          { id: 105, name: "Ukhia", bengaliName: "উখিয়া" },
          { id: 106, name: "Pekua", bengaliName: "পেকুয়া" },
          { id: 107, name: "Eidgaon", bengaliName: "ঈদগাঁও" },
        ],
      },
      {
        id: 13,
        name: "Feni",
        bengaliName: "ফেনী",
        upazilas: [
          { id: 108, name: "Chhagalnaiya", bengaliName: "ছাগলনাইয়া" },
          { id: 109, name: "Daganbhuiyan", bengaliName: "দাগনভূঞা" },
          { id: 110, name: "Feni Sadar", bengaliName: "ফেনী সদর" },
          { id: 111, name: "Parshuram", bengaliName: "পরশুরাম" },
          { id: 112, name: "Sonagazi", bengaliName: "সোনাগাজী" },
          { id: 113, name: "Fulgazi", bengaliName: "ফুলগাজী" },
        ],
      },
      {
        id: 14,
        name: "Khagrachhari",
        bengaliName: "খাগড়াছড়ি",
        upazilas: [
          { id: 114, name: "Dighinala", bengaliName: "দিঘীনালা" },
          {
            id: 115,
            name: "Khagrachhari Sadar",
            bengaliName: "খাগড়াছড়ি সদর",
          },
          { id: 116, name: "Lakshmichhari", bengaliName: "লক্ষ্মীছড়ি" },
          { id: 117, name: "Mahalchhari", bengaliName: "মহালছড়ি" },
          { id: 118, name: "Manikchhari", bengaliName: "মানিকছড়ি" },
          { id: 119, name: "Matiranga", bengaliName: "মাটিরাঙ্গা" },
          { id: 120, name: "Panchhari", bengaliName: "পানছড়ি" },
          { id: 121, name: "Ramgarh", bengaliName: "রামগড়" },
          { id: 122, name: "Guimara", bengaliName: "গুইমারা" },
        ],
      },
      {
        id: 15,
        name: "Lakshmipur",
        bengaliName: "লক্ষ্মীপুর",
        upazilas: [
          { id: 123, name: "Lakshmipur Sadar", bengaliName: "লক্ষ্মীপুর সদর" },
          { id: 124, name: "Raipur", bengaliName: "রায়পুর" },
          { id: 125, name: "Ramganj", bengaliName: "রামগঞ্জ" },
          { id: 126, name: "Ramgati", bengaliName: "রামগতি" },
          { id: 127, name: "Kamalnagar", bengaliName: "কমলনগর" },
        ],
      },
      {
        id: 16,
        name: "Noakhali",
        bengaliName: "নোয়াখালী",
        upazilas: [
          { id: 128, name: "Begumganj", bengaliName: "বেগমগঞ্জ" },
          { id: 129, name: "Noakhali Sadar", bengaliName: "নোয়াখালী সদর" },
          { id: 130, name: "Chatkhil", bengaliName: "চাটখিল" },
          { id: 131, name: "Companiganj", bengaliName: "কোম্পানীগঞ্জ" },
          { id: 132, name: "Hatiya", bengaliName: "হাতিয়া" },
          { id: 133, name: "Senbagh", bengaliName: "সেনবাগ" },
          { id: 134, name: "Sonaimuri", bengaliName: "সোনাইমুড়ি" },
          { id: 135, name: "Subarnachar", bengaliName: "সুবর্ণচর" },
          { id: 136, name: "Kabirhat", bengaliName: "কবিরহাট" },
        ],
      },
      {
        id: 17,
        name: "Rangamati",
        bengaliName: "রাঙ্গামাটি",
        upazilas: [
          { id: 137, name: "Bagaichhari", bengaliName: "বাঘাইছড়ি" },
          { id: 138, name: "Barkal", bengaliName: "বরকল" },
          {
            id: 139,
            name: "Kawkhali (Betbunia)",
            bengaliName: "কাউখালী (বেতবুনিয়া)",
          },
          { id: 140, name: "Belaichhari", bengaliName: "বেলাইছড়ি" },
          { id: 141, name: "Kaptai", bengaliName: "কাপ্তাই" },
          { id: 142, name: "Juraichhari", bengaliName: "জুরাইছড়ি" },
          { id: 143, name: "Langadu", bengaliName: "লংগদু" },
          { id: 144, name: "Naniyachar", bengaliName: "নানিয়ারচর" },
          { id: 145, name: "Rajasthali", bengaliName: "রাজস্থলী" },
          { id: 146, name: "Rangamati Sadar", bengaliName: "রাঙ্গামাটি সদর" },
        ],
      },
    ],
  },
  {
    id: 3,
    name: "Dhaka",
    bengaliName: "ঢাকা",
    districts: [
      {
        id: 18,
        name: "Dhaka",
        bengaliName: "ঢাকা",
        upazilas: [
          { id: 147, name: "Dhamrai", bengaliName: "ধামরাই" },
          { id: 148, name: "Dohar", bengaliName: "দোহার" },
          { id: 149, name: "Keraniganj", bengaliName: "কেরানীগঞ্জ" },
          { id: 150, name: "Nawabganj", bengaliName: "নবাবগঞ্জ" },
          { id: 151, name: "Savar", bengaliName: "সাভার" },
        ],
      },
      {
        id: 19,
        name: "Faridpur",
        bengaliName: "ফরিদপুর",
        upazilas: [
          { id: 152, name: "Alfadanga", bengaliName: "আলফাডাঙ্গা" },
          { id: 153, name: "Bhanga", bengaliName: "ভাঙ্গা" },
          { id: 154, name: "Boalmari", bengaliName: "বোয়ালমারী" },
          { id: 155, name: "Charbhadrasan", bengaliName: "চরভদ্রাসন" },
          { id: 156, name: "Faridpur Sadar", bengaliName: "ফরিদপুর সদর" },
          { id: 157, name: "Madhukhali", bengaliName: "মধুখালী" },
          { id: 158, name: "Nagarkanda", bengaliName: "নগরকান্দা" },
          { id: 159, name: "Sadarpur", bengaliName: "সদরপুর" },
          { id: 160, name: "Saltha", bengaliName: "সালথা" },
        ],
      },
      {
        id: 20,
        name: "Gazipur",
        bengaliName: "গাজীপুর",
        upazilas: [
          { id: 161, name: "Gazipur Sadar", bengaliName: "গাজীপুর সদর" },
          { id: 162, name: "Kaliakair", bengaliName: "কালিয়াকৈর" },
          { id: 163, name: "Kaliganj", bengaliName: "কালীগঞ্জ" },
          { id: 164, name: "Kapasia", bengaliName: "কাপাসিয়া" },
          { id: 165, name: "Sreepur", bengaliName: "শ্রীপুর" },
        ],
      },
      {
        id: 21,
        name: "Gopalganj",
        bengaliName: "গোপালগঞ্জ",
        upazilas: [
          { id: 166, name: "Gopalganj Sadar", bengaliName: "গোপালগঞ্জ সদর" },
          { id: 167, name: "Kashiani", bengaliName: "কাশিয়ানী" },
          { id: 168, name: "Kotalipara", bengaliName: "কোটালীপাড়া" },
          { id: 169, name: "Muksudpur", bengaliName: "মুকসুদপুর" },
          { id: 170, name: "Tungipara", bengaliName: "টুঙ্গিপাড়া" },
        ],
      },
      {
        id: 22,
        name: "Kishoreganj",
        bengaliName: "কিশোরগঞ্জ",
        upazilas: [
          { id: 171, name: "Austagram", bengaliName: "অষ্টগ্রাম" },
          { id: 172, name: "Bajitpur", bengaliName: "বাজিতপুর" },
          { id: 173, name: "Bhairab", bengaliName: "ভৈরব" },
          { id: 174, name: "Hossainpur", bengaliName: "হোসেনপুর" },
          { id: 175, name: "Itna", bengaliName: "ইটনা" },
          { id: 176, name: "Karimganj", bengaliName: "করিমগঞ্জ" },
          { id: 177, name: "Katiadi", bengaliName: "কটিয়াদী" },
          { id: 178, name: "Kishoreganj Sadar", bengaliName: "কিশোরগঞ্জ সদর" },
          { id: 179, name: "Kuliarchar", bengaliName: "কুলিয়ারচর" },
          { id: 180, name: "Mithamain", bengaliName: "মিঠামইন" },
          { id: 181, name: "Nikli", bengaliName: "নিকলী" },
          { id: 182, name: "Pakundia", bengaliName: "পাকুন্দিয়া" },
          { id: 183, name: "Tarail", bengaliName: "তাড়াইল" },
        ],
      },
      {
        id: 23,
        name: "Madaripur",
        bengaliName: "মাদারীপুর",
        upazilas: [
          { id: 184, name: "Rajoir", bengaliName: "রাজৈর" },
          { id: 185, name: "Madaripur Sadar", bengaliName: "মাদারীপুর সদর" },
          { id: 186, name: "Kalkini", bengaliName: "কালকিনি" },
          { id: 187, name: "Shibchar", bengaliName: "শিবচর" },
          { id: 188, name: "Dasar", bengaliName: "ডাসার" },
        ],
      },
      {
        id: 24,
        name: "Manikganj",
        bengaliName: "মানিকগঞ্জ",
        upazilas: [
          { id: 189, name: "Daulatpur", bengaliName: "দৌলতপুর" },
          { id: 190, name: "Ghior", bengaliName: "ঘিওর" },
          { id: 191, name: "Harirampur", bengaliName: "হরিরামপুর" },
          { id: 192, name: "Manikganj Sadar", bengaliName: "মানিকগঞ্জ সদর" },
          { id: 193, name: "Saturia", bengaliName: "সাটুরিয়া" },
          { id: 194, name: "Shivalaya", bengaliName: "শিবালয়" },
          { id: 195, name: "Singair", bengaliName: "সিংগাইর" },
        ],
      },
      {
        id: 25,
        name: "Munshiganj",
        bengaliName: "মুন্সিগঞ্জ",
        upazilas: [
          { id: 196, name: "Gazaria", bengaliName: "গজারিয়া" },
          { id: 197, name: "Lohajang", bengaliName: "লোহাজং" },
          { id: 198, name: "Munshiganj Sadar", bengaliName: "মুন্সিগঞ্জ সদর" },
          { id: 199, name: "Sirajdikhan", bengaliName: "সিরাজদিখান" },
          { id: 200, name: "Sreenagar", bengaliName: "শ্রীনগর" },
          { id: 201, name: "Tongibari", bengaliName: "টঙ্গীবাড়ী" },
        ],
      },
      {
        id: 26,
        name: "Narayanganj",
        bengaliName: "নারায়ণগঞ্জ",
        upazilas: [
          { id: 202, name: "Araihazar", bengaliName: "আড়াইহাজার" },
          { id: 203, name: "Bandar", bengaliName: "বন্দর" },
          {
            id: 204,
            name: "Narayanganj Sadar",
            bengaliName: "নারায়ণগঞ্জ সদর",
          },
          { id: 205, name: "Rupganj", bengaliName: "রূপগঞ্জ" },
          { id: 206, name: "Sonargaon", bengaliName: "সোনারগাঁও" },
        ],
      },
      {
        id: 27,
        name: "Narsingdi",
        bengaliName: "নরসিংদী",
        upazilas: [
          { id: 207, name: "Narsingdi Sadar", bengaliName: "নরসিংদী সদর" },
          { id: 208, name: "Belabo", bengaliName: "বেলাবো" },
          { id: 209, name: "Monohardi", bengaliName: "মনোহরদী" },
          { id: 210, name: "Palash", bengaliName: "পলাশ" },
          { id: 211, name: "Raipura", bengaliName: "রায়পুরা" },
          { id: 212, name: "Shibpur", bengaliName: "শিবপুর" },
        ],
      },
      {
        id: 28,
        name: "Rajbari",
        bengaliName: "রাজবাড়ী",
        upazilas: [
          { id: 213, name: "Baliakandi", bengaliName: "বালিয়াকান্দি" },
          { id: 214, name: "Goalandaghat", bengaliName: "গোয়ালন্দঘাট" },
          { id: 215, name: "Pangsha", bengaliName: "পাংশা" },
          { id: 216, name: "Rajbari Sadar", bengaliName: "রাজবাড়ী সদর" },
          { id: 217, name: "Kalukhali", bengaliName: "কালুখালী" },
        ],
      },
      {
        id: 29,
        name: "Shariatpur",
        bengaliName: "শরীয়তপুর",
        upazilas: [
          { id: 218, name: "Bhedarganj", bengaliName: "ভেদরগঞ্জ" },
          { id: 219, name: "Damudya", bengaliName: "ডামুড্যা" },
          { id: 220, name: "Gosairhat", bengaliName: "গোসাইরহাট" },
          { id: 221, name: "Naria", bengaliName: "নড়িয়া" },
          { id: 222, name: "Shariatpur Sadar", bengaliName: "শরীয়তপুর সদর" },
          { id: 223, name: "Zajira", bengaliName: "জাজিরা" },
        ],
      },
      {
        id: 30,
        name: "Tangail",
        bengaliName: "টাঙ্গাইল",
        upazilas: [
          { id: 224, name: "Gopalpur", bengaliName: "গোপালপুর" },
          { id: 225, name: "Basail", bengaliName: "বাসাইল" },
          { id: 226, name: "Bhuapur", bengaliName: "ভূঞাপুর" },
          { id: 227, name: "Delduar", bengaliName: "দেলদুয়ার" },
          { id: 228, name: "Ghatail", bengaliName: "ঘাটাইল" },
          { id: 229, name: "Kalihati", bengaliName: "কালিহাতী" },
          { id: 230, name: "Madhabpur", bengaliName: "মধুপুর" },
          { id: 231, name: "Mirzapur", bengaliName: "মির্জাপুর" },
          { id: 232, name: "Nagarpur", bengaliName: "নাগরপুর" },
          { id: 233, name: "Sakhipur", bengaliName: "সখীপুর" },
          { id: 234, name: "Dhanbari", bengaliName: "ধনবাড়ী" },
          { id: 235, name: "Tangail Sadar", bengaliName: "টাঙ্গাইল সদর" },
        ],
      },
    ],
  },
  {
    id: 4,
    name: "Khulna",
    bengaliName: "খুলনা",
    districts: [
      {
        id: 31,
        name: "Bagerhat",
        bengaliName: "বাগেরহাট",
        upazilas: [
          { id: 236, name: "Bagerhat Sadar", bengaliName: "বাগেরহাট সদর" },
          { id: 237, name: "Chitalmari", bengaliName: "চিতলমারী" },
          { id: 238, name: "Fakirhat", bengaliName: "ফকিরহাট" },
          { id: 239, name: "Kachua", bengaliName: "কচুয়া" },
          { id: 240, name: "Mollahat", bengaliName: "মোল্লাহাট" },
          { id: 241, name: "Mongla", bengaliName: "মোংলা" },
          { id: 242, name: "Morrelganj", bengaliName: "মোড়েলগঞ্জ" },
          { id: 243, name: "Rampal", bengaliName: "রামপাল" },
          { id: 244, name: "Sarankhola", bengaliName: "শরণখোলা" },
        ],
      },
      {
        id: 32,
        name: "Chuadanga",
        bengaliName: "চুয়াডাঙ্গা",
        upazilas: [
          { id: 245, name: "Alamdanga", bengaliName: "আলমডাঙ্গা" },
          { id: 246, name: "Chuadanga Sadar", bengaliName: "চুয়াডাঙ্গা সদর" },
          { id: 247, name: "Damurhuda", bengaliName: "দামুড়হুদা" },
          { id: 248, name: "Jibannagar", bengaliName: "জীবননগর" },
        ],
      },
      {
        id: 33,
        name: "Jashore",
        bengaliName: "যশোর",
        upazilas: [
          { id: 249, name: "Abhaynagar", bengaliName: "অভয়নগর" },
          { id: 250, name: "Bagherpara", bengaliName: "বাঘেরপাড়া" },
          { id: 251, name: "Chaugachha", bengaliName: "চৌগাছা" },
          { id: 252, name: "Jhikargachha", bengaliName: "ঝিকরগাছা" },
          { id: 253, name: "Keshabpur", bengaliName: "কেশবপুর" },
          { id: 254, name: "Jashore Sadar", bengaliName: "যশোর সদর" },
          { id: 255, name: "Manirampur", bengaliName: "মনিরামপুর" },
          { id: 256, name: "Sharsha", bengaliName: "শার্শা" },
        ],
      },
      {
        id: 34,
        name: "Jhenaidah",
        bengaliName: "ঝিনাইদহ",
        upazilas: [
          { id: 257, name: "Harinakunda", bengaliName: "হরিণাকুণ্ডু" },
          { id: 258, name: "Jhenaidah Sadar", bengaliName: "ঝিনাইদহ সদর" },
          { id: 259, name: "Kaliganj", bengaliName: "কালীগঞ্জ" },
          { id: 260, name: "Kotchandpur", bengaliName: "কোটচাঁদপুর" },
          { id: 261, name: "Maheshpur", bengaliName: "মহেশপুর" },
          { id: 262, name: "Shailkupa", bengaliName: "শৈলকুপা" },
        ],
      },
      {
        id: 35,
        name: "Khulna",
        bengaliName: "খুলনা",
        upazilas: [
          { id: 263, name: "Batiaghata", bengaliName: "বটিয়াঘাটা" },
          { id: 264, name: "Dacope", bengaliName: "দাকোপ" },
          { id: 265, name: "Dumuria", bengaliName: "ডুমুরিয়া" },
          { id: 266, name: "Dighalia", bengaliName: "দিঘলিয়া" },
          { id: 267, name: "Koyra", bengaliName: "কয়রা" },
          { id: 268, name: "Paikgachha", bengaliName: "পাইকগাছা" },
          { id: 269, name: "Phultala", bengaliName: "ফুলতলা" },
          { id: 270, name: "Rupsha", bengaliName: "রূপসা" },
          { id: 271, name: "Terokhada", bengaliName: "তেরখাদা" },
        ],
      },
      {
        id: 36,
        name: "Kushtia",
        bengaliName: "কুষ্টিয়া",
        upazilas: [
          { id: 272, name: "Bheramara", bengaliName: "ভেরামারা" },
          { id: 273, name: "Daulatpur", bengaliName: "দৌলতপুর" },
          { id: 274, name: "Khoksa", bengaliName: "খোকসা" },
          { id: 275, name: "Kumarkhali", bengaliName: "কুমারখালী" },
          { id: 276, name: "Kushtia Sadar", bengaliName: "কুষ্টিয়া সদর" },
          { id: 277, name: "Mirpur", bengaliName: "মিরপুর" },
        ],
      },
      {
        id: 37,
        name: "Magura",
        bengaliName: "মাগুরা",
        upazilas: [
          { id: 278, name: "Magura Sadar", bengaliName: "মাগুরা সদর" },
          { id: 279, name: "Mohammadpur", bengaliName: "মহম্মদপুর" },
          { id: 280, name: "Shalikha", bengaliName: "শালিখা" },
          { id: 281, name: "Sreepur", bengaliName: "শ্রীপুর" },
        ],
      },
      {
        id: 38,
        name: "Meherpur",
        bengaliName: "মেহেরপুর",
        upazilas: [
          { id: 282, name: "Gangni", bengaliName: "গাংনী" },
          { id: 283, name: "Meherpur Sadar", bengaliName: "মেহেরপুর সদর" },
          { id: 284, name: "Mujibnagar", bengaliName: "মুজিবনগর" },
        ],
      },
      {
        id: 39,
        name: "Narail",
        bengaliName: "নড়াইল",
        upazilas: [
          { id: 285, name: "Kalia", bengaliName: "কালিয়া" },
          { id: 286, name: "Lohagara", bengaliName: "লোহাগড়া" },
          { id: 287, name: "Narail Sadar", bengaliName: "নড়াইল সদর" },
        ],
      },
      {
        id: 40,
        name: "Satkhira",
        bengaliName: "সাতক্ষীরা",
        upazilas: [
          { id: 288, name: "Assasuni", bengaliName: "আশাশুনি" },
          { id: 289, name: "Debhata", bengaliName: "দেবহাটা" },
          { id: 290, name: "Kalaroa", bengaliName: "কলারোয়া" },
          { id: 291, name: "Kaliganj", bengaliName: "কালিগঞ্জ" },
          { id: 292, name: "Satkhira Sadar", bengaliName: "সাতক্ষীরা সদর" },
          { id: 293, name: "Shyamnagar", bengaliName: "শ্যামনগর" },
          { id: 294, name: "Tala", bengaliName: "তালা" },
        ],
      },
    ],
  },
  {
    id: 5,
    name: "Mymensingh",
    bengaliName: "ময়মনসিংহ",
    districts: [
      {
        id: 41,
        name: "Jamalpur",
        bengaliName: "জামালপুর",
        upazilas: [
          { id: 295, name: "Baksiganj", bengaliName: "বকশীগঞ্জ" },
          { id: 296, name: "Dewanganj", bengaliName: "দেওয়ানগঞ্জ" },
          { id: 297, name: "Islampur", bengaliName: "ইসলামপুর" },
          { id: 298, name: "Jamalpur Sadar", bengaliName: "জামালপুর সদর" },
          { id: 299, name: "Madarganj", bengaliName: "মাদারগঞ্জ" },
          { id: 300, name: "Melandaha", bengaliName: "মেলান্দহ" },
          { id: 301, name: "Sarishabari", bengaliName: "সরিষাবাড়ী" },
        ],
      },
      {
        id: 42,
        name: "Mymensingh",
        bengaliName: "ময়মনসিংহ",
        upazilas: [
          { id: 302, name: "Trishal", bengaliName: "ত্রিশাল" },
          { id: 303, name: "Dhobaura", bengaliName: "ধোবাউড়া" },
          { id: 304, name: "Fulbaria", bengaliName: "ফুলবাড়ীয়া" },
          { id: 305, name: "Gafargaon", bengaliName: "গফরগাঁও" },
          { id: 306, name: "Gauripur", bengaliName: "গৌরীপুর" },
          { id: 307, name: "Haluaghat", bengaliName: "হালুয়াঘাট" },
          { id: 308, name: "Ishwarganj", bengaliName: "ঈশ্বরগঞ্জ" },
          { id: 309, name: "Mymensingh Sadar", bengaliName: "ময়মনসিংহ সদর" },
          { id: 310, name: "Muktagachha", bengaliName: "মুক্তাগাছা" },
          { id: 311, name: "Nandail", bengaliName: "নান্দাইল" },
          { id: 312, name: "Phulpur", bengaliName: "ফুলপুর" },
          { id: 313, name: "Bhaluka", bengaliName: "ভালুকা" },
          { id: 314, name: "Tara Khanda", bengaliName: "তারাকান্দা" },
        ],
      },
      {
        id: 43,
        name: "Netrokona",
        bengaliName: "নেত্রকোণা",
        upazilas: [
          { id: 315, name: "Atpara", bengaliName: "আটপাড়া" },
          { id: 316, name: "Barhatta", bengaliName: "বারহাট্টা" },
          { id: 317, name: "Durgapur", bengaliName: "দুর্গাপুর" },
          { id: 318, name: "Khaliajuri", bengaliName: "খালিয়াজুড়ি" },
          { id: 319, name: "Kalmakanda", bengaliName: "কলমাকান্দা" },
          { id: 320, name: "Kendua", bengaliName: "কেন্দুয়া" },
          { id: 321, name: "Madan", bengaliName: "মদন" },
          { id: 322, name: "Mohanganj", bengaliName: "মোহনগঞ্জ" },
          { id: 323, name: "Netrokona Sadar", bengaliName: "নেত্রকোনা সদর" },
          { id: 324, name: "Purbadhala", bengaliName: "পূর্বধলা" },
        ],
      },
      {
        id: 44,
        name: "Sherpur",
        bengaliName: "শেরপুর",
        upazilas: [
          { id: 325, name: "Jhenaigati", bengaliName: "ঝিনাইগাতী" },
          { id: 326, name: "Nakla", bengaliName: "নকলা" },
          { id: 327, name: "Nalitabari", bengaliName: "নালিতাবাড়ী" },
          { id: 328, name: "Sherpur Sadar", bengaliName: "শেরপুর সদর" },
          { id: 329, name: "Sreebardi", bengaliName: "শ্রীবর্দী" },
        ],
      },
    ],
  },
  {
    id: 6,
    name: "Rajshahi",
    bengaliName: "রাজশাহী",
    districts: [
      {
        id: 45,
        name: "Bogura",
        bengaliName: "বগুড়া",
        upazilas: [
          { id: 330, name: "Adamdighi", bengaliName: "আদমদীঘি" },
          { id: 331, name: "Bogura Sadar", bengaliName: "বগুড়া সদর" },
          { id: 332, name: "Dhunat", bengaliName: "ধুনট" },
          { id: 333, name: "Dhupchanchia", bengaliName: "ধুপচাঁচিয়া" },
          { id: 334, name: "Gabtali", bengaliName: "গাবতলী" },
          { id: 335, name: "Kahaloo", bengaliName: "কাহালু" },
          { id: 336, name: "Nandigram", bengaliName: "নন্দীগ্রাম" },
          { id: 337, name: "Sariakandi", bengaliName: "সারিয়াকান্দি" },
          { id: 338, name: "Shajahanpur", bengaliName: "শাহজাহানপুর" },
          { id: 339, name: "Sherpur", bengaliName: "শেরপুর" },
          { id: 340, name: "Shibganj", bengaliName: "শিবগঞ্জ" },
          { id: 341, name: "Sonatola", bengaliName: "সোনাতলা" },
        ],
      },
      {
        id: 46,
        name: "Joypurhat",
        bengaliName: "জয়পুরহাট",
        upazilas: [
          { id: 342, name: "Akkelpur", bengaliName: "আক্কেলপুর" },
          { id: 343, name: "Joypurhat Sadar", bengaliName: "জয়পুরহাট সদর" },
          { id: 344, name: "Kalai", bengaliName: "কালাই" },
          { id: 345, name: "Khetlal", bengaliName: "ক্ষেতলাল" },
          { id: 346, name: "Panchbibi", bengaliName: "পাঁচবিবি" },
        ],
      },
      {
        id: 47,
        name: "Naogaon",
        bengaliName: "নওগাঁ",
        upazilas: [
          { id: 347, name: "Atrai", bengaliName: "আত্রাই" },
          { id: 348, name: "Badalgachhi", bengaliName: "বদলগাছী" },
          { id: 349, name: "Manda", bengaliName: "মান্দা" },
          { id: 350, name: "Dhamoirhat", bengaliName: "ধামইরহাট" },
          { id: 351, name: "Mohadevpur", bengaliName: "মহাদেবপুর" },
          { id: 352, name: "Naogaon Sadar", bengaliName: "নওগাঁ সদর" },
          { id: 353, name: "Niamatpur", bengaliName: "নিয়ামতপুর" },
          { id: 354, name: "Patnitala", bengaliName: "পত্নীতলা" },
          { id: 355, name: "Porsha", bengaliName: "পোরশা" },
          { id: 356, name: "Raninagar", bengaliName: "রাণীনগর" },
          { id: 357, name: "Sapahar", bengaliName: "সাপাহার" },
        ],
      },
      {
        id: 48,
        name: "Natore",
        bengaliName: "নাটোর",
        upazilas: [
          { id: 358, name: "Bagatipara", bengaliName: "বাগাতিপাড়া" },
          { id: 359, name: "Baraigram", bengaliName: "বড়াইগ্রাম" },
          { id: 360, name: "Gurudaspur", bengaliName: "গুরুদাসপুর" },
          { id: 361, name: "Lalpur", bengaliName: "লালপুর" },
          { id: 362, name: "Natore Sadar", bengaliName: "নাটোর সদর" },
          { id: 363, name: "Singra", bengaliName: "সিংড়া" },
          { id: 364, name: "Naldanga", bengaliName: "নলডাঙ্গা" },
        ],
      },
      {
        id: 49,
        nam4e: "Chapai Nawabganj",
        bengaliName: "চাঁপাইনবাবগঞ্জ",
        upazilas: [
          { id: 365, name: "Bholahat", bengaliName: "ভোলাহাট" },
          { id: 366, name: "Gomastapur", bengaliName: "গোমস্তাপুর" },
          { id: 367, name: "Nachole", bengaliName: "নাচোল" },
          { id: 368, name: "Nawabganj Sadar", bengaliName: "নবাবগঞ্জ সদর" },
          { id: 369, name: "Shibganj", bengaliName: "শিবগঞ্জ" },
        ],
      },
      {
        id: 50,
        name: "Pabna",
        bengaliName: "পাবনা",
        upazilas: [
          { id: 370, name: "Atgharia", bengaliName: "আটঘরিয়া" },
          { id: 371, name: "Bera", bengaliName: "বেড়া" },
          { id: 372, name: "Bhangura", bengaliName: "ভাঙ্গুড়া" },
          { id: 373, name: "Chatmohar", bengaliName: "চাটমোহর" },
          { id: 374, name: "Faridpur", bengaliName: "ফরিদপুর" },
          { id: 375, name: "Ishwardi", bengaliName: "ঈশ্বরদী" },
          { id: 376, name: "Pabna Sadar", bengaliName: "পাবনা সদর" },
          { id: 377, name: "Santhia", bengaliName: "সাঁথিয়া" },
          { id: 378, name: "Sujanagar", bengaliName: "সুজানগর" },
        ],
      },
      {
        id: 51,
        name: "Rajshahi",
        bengaliName: "রাজশাহী",
        upazilas: [
          { id: 379, name: "Bagha", bengaliName: "বাঘা" },
          { id: 380, name: "Bagmara", bengaliName: "বাগমারা" },
          { id: 381, name: "Charghat", bengaliName: "চারঘাট" },
          { id: 382, name: "Durgapur", bengaliName: "দুর্গাপুর" },
          { id: 383, name: "Godagari", bengaliName: "গোদাগাড়ী" },
          { id: 384, name: "Mohanpur", bengaliName: "মোহনপুর" },
          { id: 385, name: "Paba", bengaliName: "পবা" },
          { id: 386, name: "Puthia", bengaliName: "পুঠিয়া" },
          { id: 387, name: "Tanore", bengaliName: "তানোর" },
        ],
      },
      {
        id: 52,
        name: "Sirajganj",
        bengaliName: "সিরাজগঞ্জ",
        upazilas: [
          { id: 388, name: "Belkuchi", bengaliName: "বেলকুচি" },
          { id: 389, name: "Chauhali", bengaliName: "চৌহালী" },
          { id: 390, name: "Kamarkhanda", bengaliName: "কামারখন্দ" },
          { id: 391, name: "Kazipur", bengaliName: "কাজীপুর" },
          { id: 392, name: "Raiganj", bengaliName: "রায়গঞ্জ" },
          { id: 393, name: "Shahjadpur", bengaliName: "শাহজাদপুর" },
          { id: 394, name: "Sirajganj Sadar", bengaliName: "সিরাজগঞ্জ সদর" },
          { id: 395, name: "Tarash", bengaliName: "তাড়াশ" },
          { id: 396, name: "Ullahpara", bengaliName: "উল্লাপাড়া" },
        ],
      },
    ],
  },
  {
    id: 7,
    name: "Rangpur",
    bengaliName: "রংপুর",
    districts: [
      {
        id: 53,
        name: "Dinajpur",
        bengaliName: "দিনাজপুর",
        upazilas: [
          { id: 397, name: "Birampur", bengaliName: "বিরামপুর" },
          { id: 398, name: "Birganj", bengaliName: "বীরগঞ্জ" },
          { id: 399, name: "Biral", bengaliName: "বিরাল" },
          { id: 400, name: "Bochaganj", bengaliName: "বোচাগঞ্জ" },
          { id: 401, name: "Chirirbandar", bengaliName: "চিরিরবন্দর" },
          { id: 402, name: "Phulbari", bengaliName: "ফুলবাড়ী" },
          { id: 403, name: "Ghoraghat", bengaliName: "ঘোড়াঘাট" },
          { id: 404, name: "Hakimpur", bengaliName: "হাকিমপুর" },
          { id: 405, name: "Kaharole", bengaliName: "কাহারোল" },
          { id: 406, name: "Khansama", bengaliName: "খানসামা" },
          { id: 407, name: "Dinajpur Sadar", bengaliName: "দিনাজপুর সদর" },
          { id: 408, name: "Nawabganj", bengaliName: "নবাবগঞ্জ" },
          { id: 409, name: "Parbatipur", bengaliName: "পার্বতীপুর" },
        ],
      },
      {
        id: 54,
        name: "Gaibandha",
        bengaliName: "গাইবান্ধা",
        upazilas: [
          { id: 410, name: "Phulchhari", bengaliName: "ফুলছড়ি" },
          { id: 411, name: "Gaibandha Sadar", bengaliName: "গাইবান্ধা সদর" },
          { id: 412, name: "Gobindaganj", bengaliName: "গোবিন্দগঞ্জ" },
          { id: 413, name: "Palashbari", bengaliName: "পলাশবাড়ী" },
          { id: 414, name: "Sadullapur", bengaliName: "সাদুল্লাপুর" },
          { id: 415, name: "Sughatta", bengaliName: "সুghatta" },
          { id: 416, name: "Sundarganj", bengaliName: "সুন্দরগঞ্জ" },
        ],
      },
      {
        id: 55,
        name: "Kurigram",
        bengaliName: "কুড়িগ্রাম",
        upazilas: [
          { id: 417, name: "Bhurungamari", bengaliName: "ভুরুঙ্গামারী" },
          { id: 418, name: "Char Rajibpur", bengaliName: "চর রাজিবপুর" },
          { id: 419, name: "Chilmari", bengaliName: "চিলমারী" },
          { id: 420, name: "Phulbari", bengaliName: "ফুলবাড়ী" },
          { id: 421, name: "Kurigram Sadar", bengaliName: "কুড়িগ্রাম সদর" },
          { id: 422, name: "Nageshwari", bengaliName: "নাগেশ্বরী" },
          { id: 423, name: "Rajarhat", bengaliName: "রাজারহাট" },
          { id: 424, name: "Raomari", bengaliName: "রাওমারী" },
          { id: 425, name: "Ulipur", bengaliName: "উলিপুর" },
        ],
      },
      {
        id: 56,
        name: "Lalmonirhat",
        bengaliName: "লালমনিরহাট",
        upazilas: [
          { id: 426, name: "Aditmari", bengaliName: "আদিতমারী" },
          { id: 427, name: "Hatibandha", bengaliName: "হাতীবান্ধা" },
          { id: 428, name: "Kaliganj", bengaliName: "কালীগঞ্জ" },
          { id: 429, name: "Lalmonirhat Sadar", bengaliName: "লালমনিরহাট সদর" },
          { id: 430, name: "Patgram", bengaliName: "পাটগ্রাম" },
        ],
      },
      {
        id: 57,
        name: "Nilphamari",
        bengaliName: "নীলফামারী",
        upazilas: [
          { id: 431, name: "Dimla", bengaliName: "ডিমলা" },
          { id: 432, name: "Domar", bengaliName: "ডোমার" },
          { id: 433, name: "Jaldhaka", bengaliName: "জলঢাকা" },
          { id: 434, name: "Kishoreganj", bengaliName: "কিশোরগঞ্জ" },
          { id: 435, name: "Nilphamari Sadar", bengaliName: "নীলফামারী সদর" },
          { id: 436, name: "Saidpur", bengaliName: "সৈয়দপুর" },
        ],
      },
      {
        id: 58,
        name: "Panchagarh",
        bengaliName: "পঞ্চগড়",
        upazilas: [
          { id: 437, name: "Atwari", bengaliName: "আটোয়ারী" },
          { id: 438, name: "Boda", bengaliName: "বোদা" },
          { id: 439, name: "Debiganj", bengaliName: "দেবীগঞ্জ" },
          { id: 440, name: "Panchagarh Sadar", bengaliName: "পঞ্চগড় সদর" },
          { id: 441, name: "Tetulia", bengaliName: "তেঁতুলিয়া" },
        ],
      },
      {
        id: 59,
        name: "Rangpur",
        bengaliName: "রংপুর",
        upazilas: [
          { id: 442, name: "Badarganj", bengaliName: "বদরগঞ্জ" },
          { id: 443, name: "Gangachhara", bengaliName: "গংগাচড়া" },
          { id: 444, name: "Kaunia", bengaliName: "কউনিয়া" },
          { id: 445, name: "Mithapukur", bengaliName: "মিঠাপুকুর" },
          { id: 446, name: "Pirgachha", bengaliName: "পীরগাছা" },
          { id: 447, name: "Pirganj", bengaliName: "পীরগঞ্জ" },
          { id: 448, name: "Rangpur Sadar", bengaliName: "রংপুর সদর" },
          { id: 449, name: "Taraganj", bengaliName: "তারাগঞ্জ" },
        ],
      },
      {
        id: 60,
        name: "Thakurgaon",
        bengaliName: "ঠাকুরগাঁও",
        upazilas: [
          { id: 450, name: "Baliadangi", bengaliName: "বালিয়াডাঙ্গী" },
          { id: 451, name: "Haripur", bengaliName: "হরিপুর" },
          { id: 452, name: "Pirganj", bengaliName: "পীরগঞ্জ" },
          { id: 453, name: "Ranisankail", bengaliName: "রাণীশংকাইল" },
          { id: 454, name: "Thakurgaon Sadar", bengaliName: "ঠাকুরগাঁও সদর" },
        ],
      },
    ],
  },
  {
    id: 8,
    name: "Sylhet",
    bengaliName: "সিলেট",
    districts: [
      {
        id: 61,
        name: "Habiganj",
        bengaliName: "হবিগঞ্জ",
        upazilas: [
          { id: 455, name: "Ajmiriganj", bengaliName: "আজমিরীগঞ্জ" },
          { id: 456, name: "Bahubal", bengaliName: "বাহুবল" },
          { id: 457, name: "Baniyachong", bengaliName: "বানিয়াচং" },
          { id: 458, name: "Chunarughat", bengaliName: "চুনারুঘাট" },
          { id: 459, name: "Habiganj Sadar", bengaliName: "হবিগঞ্জ সদর" },
          { id: 460, name: "Lakhai", bengaliName: "লাখাই" },
          { id: 461, name: "Madhabpur", bengaliName: "মাধবপুর" },
          { id: 462, name: "Nabiganj", bengaliName: "নবীগঞ্জ" },
          { id: 463, name: "Shayestaganj", bengaliName: "শায়েস্তাগঞ্জ" },
        ],
      },
      {
        id: 62,
        name: "Moulvibazar",
        bengaliName: "মৌলভীবাজার",
        upazilas: [
          { id: 464, name: "Barlekha", bengaliName: "বড়লেখা" },
          { id: 465, name: "Juri", bengaliName: "জুড়ী" },
          { id: 466, name: "Kamalganj", bengaliName: "কমলগঞ্জ" },
          { id: 467, name: "Kulaura", bengaliName: "কুলাউড়া" },
          { id: 468, name: "Moulvibazar Sadar", bengaliName: "মৌলভীবাজার সদর" },
          { id: 469, name: "Rajnagar", bengaliName: "রাজনগর" },
          { id: 470, name: "Sreemangal", bengaliName: "শ্রীমঙ্গল" },
        ],
      },
      {
        id: 63,
        name: "Sunamganj",
        bengaliName: "সুনামগঞ্জ",
        upazilas: [
          { id: 471, name: "Bishwamvarpur", bengaliName: "বিশ্বম্ভরপুর" },
          { id: 472, name: "Chhatak", bengaliName: "ছাতক" },
          { id: 473, name: "Shantiganj", bengaliName: "শান্তিগঞ্জ" },
          { id: 474, name: "Derai", bengaliName: "দিরাই" },
          { id: 475, name: "Dharamapasha", bengaliName: "ধরমপাশা" },
          { id: 476, name: "Dowarabazar", bengaliName: "দোয়ারাবাজার" },
          { id: 477, name: "Jagannathpur", bengaliName: "জগন্নাথপুর" },
          { id: 478, name: "Jamalganj", bengaliName: "জামালগঞ্জ" },
          { id: 479, name: "Sullah", bengaliName: "শাল্লা" },
          { id: 480, name: "Sunamganj Sadar", bengaliName: "সুনামগঞ্জ সদর" },
          { id: 481, name: "Tahirpur", bengaliName: "তাহিরপুর" },
          { id: 482, name: "Madhyanagar", bengaliName: "মধ্যনগর" },
        ],
      },
      {
        id: 64,
        name: "Sylhet",
        bengaliName: "সিলেট",
        upazilas: [
          { id: 483, name: "Balaganj", bengaliName: "বালাগঞ্জ" },
          { id: 484, name: "Beanibazar", bengaliName: "বিয়ানীবাজার" },
          { id: 485, name: "Bishwanath", bengaliName: "বিশ্বনাথ" },
          { id: 486, name: "Companiganj", bengaliName: "কোম্পানীগঞ্জ" },
          { id: 487, name: "Dakshin Surma", bengaliName: "দক্ষিণ সুরমা" },
          { id: 488, name: "Fenchuganj", bengaliName: "ফেঞ্চুগঞ্জ" },
          { id: 489, name: "Golapganj", bengaliName: "গোলাপগঞ্জ" },
          { id: 490, name: "Gowainghat", bengaliName: "গোয়াইনঘাট" },
          { id: 491, name: "Jaintiapur", bengaliName: "জৈন্তাপুর" },
          { id: 492, name: "Kanaighat", bengaliName: "কানাইঘাট" },
          { id: 493, name: "Osmani Nagar", bengaliName: "ওসমানীনগর" },
          { id: 494, name: "Sylhet Sadar", bengaliName: "সিলেট সদর" },
          { id: 495, name: "Zakiganj", bengaliName: "জকিগঞ্জ" },
        ],
      },
    ],
  },
];

export default divisions;